### PR TITLE
Add websocket and secure websocket support for standalone server

### PR DESCRIPTION
**Pull request by edwardchoh**
Add ws and wss support for surgemq standalone. Also added a README.md file to explain usage and examples.

### CODE REVIEW

**Comment by zhenjl** [comment]
wow...this is awesome...i haven't gone thru the details yet but this is much appreciated...

will review over the next day or two...

**Comment by zhenjl** [comment]
@edwardchoh I am so sorry about this delay. Is this still good to merge? Also, in your testing does it work as expected? I don't have any means to run tests for this so I will have to trust you on this. Thanks!

**Comment by zhenjl** [comment]
@edwardchoh Thank you for the contributions. Please don't forget to add yourself to the AUTHORS file.

**Comment by edwardchoh** [comment]
The commit has been tested with HiveMQ websocket client at http://www.hivemq.com/demos/websocket-client/ and both publish/receive with patterns work as intended.

**Comment by zhenjl** [comment]
Thanks @edwardchoh

**Comment by shalinkktl** [comment]
@edwardchoh I just tried using hivemq websocket client to test the websocket connectivity and I am facing issues. Please check the following screen shot. 
I am getting the error : **WebSocket connection to 'ws://localhost:7654/mqtt' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED**
I used the following command to execute the script.
`./surgemq -wsaddr="7654"`

Am I doing something wrong ?

screenshot from 2015-11-04 16 15 09

**Comment by shalinkktl** [comment]
Oops my bad. I missed the ":" in the port. It is working when I changed the command to 
`./surgemq -wsaddr=":7654"`

**Pull request merged**
